# Generated by Django 4.1.7 on 2023-02-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catflix_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='categories',
            new_name='category',
        ),
    ]
